import { site } from "@/lib/site";

export function Footer() {
  return (
    <footer className="border-t border-line bg-panel/60">
      <div className="mx-auto max-w-6xl px-4 py-12 sm:px-6">
        <div className="flex flex-col gap-8 md:flex-row md:items-start md:justify-between">
          <div>
            <div className="font-display text-lg font-bold text-bone">
              <span className="text-phosphor">$</span>PREDICTIONS
              <span className="animate-blink text-phosphor">_</span>
            </div>
            <p className="mt-2 max-w-md text-xs leading-relaxed text-fog">
              Claude reads the markets. You take the trades. Built by degens, audited by no one.
            </p>
          </div>
          <div className="text-xs leading-relaxed text-fog">
            <div className="mb-2 tracking-[0.3em] text-fog/70">PIPES</div>
            <p>
              Market data: Polymarket public API
              <br />
              Oracle: Claude API
              <br />
              Feed:{" "}
              <a href="/api/predictions" className="text-phosphor hover:underline">
                /api/predictions
              </a>
            </p>
          </div>
        </div>
        <p className="mt-10 border-t border-line pt-6 text-[11px] leading-relaxed text-fog/70">
          NOT FINANCIAL ADVICE. {site.name} is an experiment in AI-assisted market reading, plus a
          memecoin. Signals are generated by an AI model (or, in quant mode, a simple heuristic)
          and can be confidently wrong. Prediction markets carry real risk of loss; memecoins
          carry total risk of loss. Never trade money you can&apos;t afford to lose. This project
          is not affiliated with, endorsed by, or connected to Polymarket or Anthropic. Do your
          own research.
        </p>
      </div>
    </footer>
  );
}
